# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sukko < Formula
  desc "Sukko WebSocket platform CLI"
  homepage "https://github.com/sukko-dev/cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.0/sukko_1.0.0_darwin_amd64.tar.gz"
      sha256 "3b609dedb3042c4865bd70e1244da906d5c7681b274fc04d8afc349e1e4730a7"

      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.0/sukko_1.0.0_darwin_arm64.tar.gz"
      sha256 "90be2dd33cdbd863cdb7af7f55cddc781c487224e12ccb09836cd7bbd6b1eacb"

      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.0/sukko_1.0.0_linux_amd64.tar.gz"
      sha256 "19d9c98fd441a6f8c32d6dcca68903c9dbaa77b4bd9018f1928eb13c8ed21105"
      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.0/sukko_1.0.0_linux_arm64.tar.gz"
      sha256 "87752c7d3100f991b129a4c80d71acff83a9b8552ed851557de7016742c1db6e"
      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
  end

  test do
    system "#{bin}/sukko", "version"
  end
end
