# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sukko < Formula
  desc "Sukko WebSocket platform CLI"
  homepage "https://github.com/sukko-dev/cli"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.1/sukko_1.0.1_darwin_amd64.tar.gz"
      sha256 "60efdc3f78de5f64a03e2b5b7ba689415db740a0782a429591dfcd56a8d24f02"

      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.1/sukko_1.0.1_darwin_arm64.tar.gz"
      sha256 "6788e5ce3ec0c31269c6dcd86c15ef0b8a4a3b2b76766e0936beb0cf9e4b3466"

      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.1/sukko_1.0.1_linux_amd64.tar.gz"
      sha256 "f1cc5c07c40b39fb536787c64cf0b8df59436cb2a6c6a233b36320a3f9d7ed70"
      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.1/sukko_1.0.1_linux_arm64.tar.gz"
      sha256 "1af19e33564aa2ecd90d1b2bdbca6b939b52b9ba8942a93541857313199339ff"
      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
  end

  test do
    system "#{bin}/sukko", "version"
  end
end
