# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sukko < Formula
  desc "Sukko WebSocket platform CLI"
  homepage "https://github.com/sukko-dev/cli"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.2/sukko_1.0.2_darwin_amd64.tar.gz"
      sha256 "517b25a60238fdf5753ceaa8b1e25489e1c95aef6861d0ea80e4c30a83cf6a1e"

      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.2/sukko_1.0.2_darwin_arm64.tar.gz"
      sha256 "e42d687d9780833f2c5bce896dfeed01e0c580b2995c40e97daa61b3dbc33bec"

      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.2/sukko_1.0.2_linux_amd64.tar.gz"
      sha256 "537bdb21bb1717ea27a869c7dd8221ed20c4f5c1e6286fe32dcc3fc0de45f63b"
      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sukko-dev/cli/releases/download/v1.0.2/sukko_1.0.2_linux_arm64.tar.gz"
      sha256 "5b4126e3be3fd44792c37ee8063d884387fe00f95158891938072222d10e6dd2"
      define_method(:install) do
        bin.install "sukko"
        generate_completions_from_executable(bin/"sukko", "completion")
      end
    end
  end

  test do
    system "#{bin}/sukko", "version"
  end
end
